global:
  scrape_interval: 5s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs: [ { targets: ['backend:8000'] } ]
rule_files: [ /etc/prometheus/alert_rules.yml ]
